
--
-- Table structure for table `notes`
--

CREATE TABLE `notes` (
  `id` char(36) NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `university` varchar(255) NOT NULL,
  `photo` varchar(255) NOT NULL,
  `degree` varchar(255) NOT NULL,
  `area` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `cv` varchar(255) NOT NULL DEFAULT 'default_value',
  `accept` tinyint(1) NOT NULL,
  `referral` varchar(30) DEFAULT NULL,
  `linkedin` varchar(255) NOT NULL DEFAULT '',
  `other_links` varchar(255) NOT NULL DEFAULT '',
  `is_published` tinyint(1) NOT NULL DEFAULT 0,
  `heart_count` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `notes`
--

INSERT INTO `notes` (`id`, `user_id`, `name`, `email`, `university`, `photo`, `degree`, `area`, `description`, `cv`, `accept`, `referral`, `linkedin`, `other_links`, `is_published`, `heart_count`, `created_at`, `updated_at`) VALUES
('9b36a527-f06e-4808-970a-eb3626ae891e', 2, 'William Padilha', 'williampadilhalemes@gmail.com', 'University of Debrecen', 'photos/go3hDgr3R1qCDvPWiGONGnISzfG7pH1STHzJymkQ.jpg', 'Msc Biology', 'Science and Technology', 'I am a Msc Biology student passionate about continuous learning and staying up-to-date with the latest trends in my study area, including techonology and management. I am a strong communicator adept at simplifying complex ideas for diverse audiences. I thoroughly enjoy collaborative teamwork and excel as a detail-oriented problem solver with a knack for analytical thinking. Eager to collaborate with like-minded professionals and contribute to innovative projects that push boundaries and drive growth', 'curriculums/yjU2TJDgumIJbBA7tKooEUEDyoc7cquA8aNLxbYJ.pdf', 1, NULL, '', '', 0, 0, '2024-01-30 04:46:53', '2024-02-01 20:03:06'),
('9b36a875-7ffb-4c2c-93d1-29dcbfb15fe1', 3, 'Mostafa Eltantawy', 'mostafaessamabdelhady@gmail.com', 'University of Debrecen', 'photos/KR1da517O908E3Tj9QiEnB0qd8W37zawTU7LJbq3.jpg', 'Biochemical engineering', 'Engineering', 'I\'m Mostafa Essam, twenty one years old Biochemical engineering student at university of Debrecen.\nI\'m going to start my third year of the course next semester which will be a milestone for me to get nearer and nearer to kick start my career, Interested in renewable and sustainable energy and all chemical industries that change into sustainable one\'s. Honestly I don\'t have that type of experience any company seeks but I\'m enthusiastic and a fast learner who prefers hard work over talent.\nOpen for any type of student jobs and of course it\'s preferred to be relatable to my field of studies and interest', 'curriculums/yGKMkSPTMbz15dxDXvBNdd0EtfsT9CMKq4qXFJuh.pdf', 1, NULL, 'https://www.linkedin.com/in/mostafa-eltantawy-973032244', '', 0, 0, '2024-01-30 04:56:08', '2024-02-01 20:03:19'),
('9b36ac26-1d85-4716-b470-f4693fe02e90', 4, 'Rustamli Nijat', 'nijatrstm@gmail.com', 'University of Debrecen', 'photos/blv00wLCowbTaHHLY4XNTp8egfC4uIslweJT9bFW.jpg', 'Computer Science Engineering ', 'Informatics', 'I\'ve been all about making things top-notch. From making sure lesson plans shine at Tuttify.io, to helping launch Hungary\'s first junior enterprise at BioNexus, I\'ve been hands-on in shaping quality and talent.\n\nI\'ve also been behind the scenes at REBEL Internet, making websites run like clockwork. And back when I was at Lotfizadeh Technology Center, I was the one folks turned to for solving problems, answering questions, and handling tech stuff.\n\nIf you\'re looking for someone who\'s all about quality, teamwork, and getting things done, I\'m here and ready to roll!', 'curriculums/Lz6Ll77OgpPX1CjQB0QlRBIb6N94xmcoV02yvXT0.pdf', 1, NULL, 'https://www.linkedin.com/in/nijat-rustamli-a14457206', '', 0, 0, '2024-01-30 05:06:27', '2024-02-01 20:05:35'),
('9b3bff1b-6ea4-4482-8c1e-1d8af315d78f', 6, 'Syahadana Putra Yuzansa ', 'yuzansa@gmail.com', 'University of Debrecen', 'photos/XIMEKAGwUumEnBszpfoQlnbwLi6NWtlGcmxqScQ1.jpg', 'Food Safety and Quality Engineering', 'Agriculture, Food Sciences and Environmental Management', 'I am currently pursuing a Master\'s Degree at the University of Debrecen. I have a particular interest in the field of microbiology, food safety, and biotechnology. I have the experience of working in laboratory settings from my time inside and outside Europe. I am very keen to broaden my knowledge and experience by working in a company in Europe.\n', 'curriculums/tNeZTbhdRwQL4apkpN0rRWMaxw9loR0UHlgl99PN.pdf', 1, NULL, 'https://www.linkedin.com/in/syahadana-putra-y-1b9002139', '', 0, 0, '2024-02-01 20:37:33', '2024-02-01 20:37:33'),
('9b3c00b5-9e3f-48b8-a12d-4dde4e39eb8d', 7, 'Ana Júlia Sandri', 'anajuliasandri@gmail.com', 'University of Debrecen', 'photos/wvfrlJUXeWiGFQkUBxktnMwbj9hpDCSHjATeTZEm.png', 'Msc Public Health', 'Health Sciences', 'Nurse, MBA Strategic People Management, with experience in coordination of a health public institution, specialized in primary care and health promotion. Training and supervising the activities of the technical team. Provide direct assistance to patients, carry out consultations, request laboratory tests and prescribe medication. Promote actions for disease prevention. Carry out care actions for children, women, adolescents, adults and the elderly. Provision of material resources.\n', 'curriculums/nQNajhw2DCWP4aqQohxoZF96kWO3QuPlKsig8reW.pdf', 1, NULL, '', '', 0, 0, '2024-02-01 20:42:02', '2024-02-01 20:42:02'),
('9b3c0224-13f1-4773-8b2f-25b29faafe4b', 8, 'Alisa Burova', 'alica.burova@gmail.com', 'University of Debrecen', 'photos/iesjdmRwH4aWZMZA3Z0rEtB3ooMHCCZ0uGiOaR74.jpg', 'Biochemical Engineering BSc', 'Engineering', 'I am interested in very different areas of Biology: Genetics, Biochemistry, Microbiology, Molecular biology etc and now I would be glad to try myself in any of this areas. As I am a second year student I would like to find a work when I can start my research work and make my future area of study more concrete.\n', 'curriculums/MWul6L0PlKVbFZa4CnBx23sjsPUx8Gj2SCHX1iD9.pdf', 1, NULL, 'https://www.linkedin.com/in/alisa-burova', '', 0, 0, '2024-02-01 20:46:02', '2024-02-01 20:46:02'),
('9b3c0321-804d-4082-b755-c1f19ecab680', 9, 'Brayam Porphirio ', 'porphirio.brayam@gmail.com', 'University of Debrecen', 'photos/h33gOl2RElJyY53puS0zeUcbjPBFBgH1mDNK5hJY.jpg', 'Biomérnök ', 'Engineering', 'IT fields, applied science fields, teaching skills \n', 'curriculums/Gl8F46pzXCAn4F486lZbXPoxRtmawSGrdWrl6RVM.pdf', 1, NULL, '', '', 0, 0, '2024-02-01 20:48:48', '2024-02-01 20:48:48'),
('9b3c0620-52f1-4c76-9c34-1973d20d5d00', 10, 'Juliana Ribeiro', 'julianafr94@gmil.com', 'University of Debrecen', 'photos/xgNmKe3wq4jtlUCB9jnId5tIMlBP6nHvavOIyr2l.jpg', 'Msc. Biotechnology', 'Health Sciences', 'Pharmacist, post-graduate in neuroscience and behaviour and currently pursuing a Pharmaceutical biotechnology Master\'s degree at the University of Pécs, Hungary. My experience includes research in biochemistry, quality control of finished products and cosmetics, drug manipulation, scientific writing and delivering high-quality pharmaceutical care, and facilitating access to health promotion information for patients and my community.\nI have previous experience as a teaching assistant and supervised the internship of a pharmacy student in her last semester at a hospital. My primary skills include analytic capacity, Leadership, Communication, Teamwork, Project Management, Problem-Solving, Time and Conflict Management.', 'curriculums/eXubnilL1K5Oj4yHRH8sgoqYexuelWnaaUb7JhCg.pdf', 1, NULL, 'https://www.linkedin.com/in/juliana-fuhr-pharmacist/', '', 0, 0, '2024-02-01 20:57:11', '2024-02-01 20:57:11'),
('9b3c0820-48cd-48a4-aab0-cbb76b27c314', 11, 'Nicolas Grijalva-Borja', 'nicolasgrijalva13@gmail.com', 'University of Debrecen', 'photos/u13oOAhMZgGhj5ffb2um0YKTfSSmla5w6Y6CXSYG.jpg', 'MSc Molecular Biology', 'Science and Technology', 'I am a master\'s student currently pursuing my studies in Debrecen, Hungary, where I am honing my passion for science. With a strong foundation in laboratory techniques and a deep understanding of project management, I am well-equipped to contribute effectively to scientific endeavors.\nMy approach to career opportunities is characterized by an open-mindedness and eagerness to explore new avenues. I am excited to embark on new challenges and contribute my skills and knowledge to meaningful projects.\n', 'curriculums/GvhAk0ZupJ1zGzCA7a2qchhB3LPCY0rRtURaJrcc.pdf', 1, NULL, 'https://www.linkedin.com/in/nicolasgrijalvaborja/', '', 0, 0, '2024-02-01 21:02:46', '2024-02-01 21:02:46'),
('9b3c0a81-28eb-420f-afa0-90367f2da01c', 12, 'Pavle Veljovic', 'pveljovic2002@gmail.com', 'University of Debrecen', 'photos/MbhTdw6wf6X68EpEHDF75k8GdTdcsUjF8jTXlquf.jpg', 'Biochemical Engineering BSc', 'Engineering', 'My name is Veljovic Pavle, I come from Serbia and am currently pursuing my bachelor\'s degree at the University of Debrecen in the field of Biochemical Engineering. \n', 'default_value', 1, NULL, 'http://linkedin.com/in/pavle-veljovic-93b1b9256', '', 0, 0, '2024-02-01 21:09:25', '2024-02-01 21:09:25'),
('9b3c6beb-cd2f-422d-87d4-744180df797f', 13, 'Jelena Ye', 'jelenaye02@gmail.com', 'University of Debrecen', 'photos/YnlvFyj3WBtSnQabZuzSmfzznRcpUqATGLVgdRAX.jpg', 'Business Administration and Management ', 'Economics and Business', 'I\'m a business major with a passion for strategy and innovation. My career goal is to excel in a corporate setting, leveraging my skills in market analysis, financial modeling, and strategic planning. I thrive on problem-solving and collaborative teamwork, aiming to contribute to a company\'s growth and success.\n', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-02 01:41:49', '2024-02-02 01:41:49'),
('9b3c6d89-5d30-4dc7-b854-8ba824671882', 14, 'Arutiun Vardanean', 'arutiunvard@gmail.com', 'University of Debrecen', 'photos/UIukDj0eDPCWG5rK5ytxVY2Zl4T6MH806cl043xD.jpg', 'Biochemical Engineering BSc', 'Engineering', 'My name is Arutiun. I am 20 years old. I am studying Biochemical Engineering BSc, third semester.  My goal is to find a job related to my studies, e.g. lab worker. Also I am very interested in tutoring for school students: Chemistry, Math, English, other subjects are negotiable.\n', 'curriculums/QNbHT158WfQvZUnbAymF0cNHvKeZXboZGRZGqSfn.pdf', 1, NULL, '', '', 0, 0, '2024-02-02 01:46:20', '2024-02-02 01:46:20'),
('9b3c71c0-175b-4d5c-b06f-63ea2d0a7899', 15, 'Zhanibek Tokmurzin', 'zhanibektokmurzin@gmail.com', 'University of Debrecen', 'photos/GC9QZzzgxCUAvPfx7JxLIlhdsf9oz5tproNL7OPi.jpg', 'Business Administration ', 'Economics and Business', 'Hello, I am a student at University at Debrecen and majoring in Business Administration 7 Economics. Beginning from high school I was enjoying pure math, finances and economics. I wrote an economic research related to my home country Kazakhstan. I know fluently Kazakh, Russian and English languages. Also, I am great user of Excel and Powerpoint. I love to do speeches and present my new ideas.\n', 'curriculums/0RQQPNI7tnAEiRioLmy4d4Jb3vl7Q1OiP46lw5lF.pdf', 1, NULL, 'https://www.linkedin.com/in/zhanibek-tokmurzin-603182207/', '', 0, 0, '2024-02-02 01:58:07', '2024-02-02 01:58:07'),
('9b3c7467-c0bd-4e8d-bac0-931a7d862074', 16, 'Wellinton Wellinton', 'wellintonscheffer@gmail.com', 'Óbuda University', 'photos/O7beMdFNSW9AIfsUI0bzBSmDdo35jF6XsIMerUr7.jpg', 'Mechanical Engineering BSc', 'Engineering', '-My learning is fast;\n-I have knowledge of different types of software, including: MatLab; Ansys; SolidWorks; FreeCad; TinkerCad; EasyEda; Inventor; Catia; AutoCad; Python; Festo FluidSIM; Latex; OpenFOAM, Excel (Advanced, I have knowledge in VBA among several other tools present.), Microsoft 365 (Advanced)\n- I speak English (B2) and my native language is Portuguese (I\'m Brazilian), I have a brief knowledge of Spanish/German;\n-Currently my degree is in the area of mechanical engineering, but I have knowledge, in addition to this area, in IT (which I studied some subjects in college and sought more knowledge on my own), accounting (which I studied some subjects in college);\n-I am extremely sociable, I like to demonstrate my service and keep my learning constant.', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-02 02:05:32', '2024-02-02 02:05:32'),
('9b3c75b2-7492-4b0c-b49d-5c5565e57e14', 17, 'Balázs Fábián', 'fabian.balazs.krisztian@gmail.com', 'University of Debrecen', 'photos/ZVg8Xav54PJ3ETEJEujXiLrJV4IbHXQkGcK3XzMS.jpg', 'Biomérnök Msc', 'Engineering', 'Frissen diplomázott, mesterszakos biomérnök vagyok. Elsősorban a gyógyszeripar minőségbiztosítási területén keresek munkát. Erősségeim a precizitás, jó problémamegoldó képesség és a csapatban való munka! \n', 'curriculums/o6G8d9e15NxZmLzPz0uqHmXCBAJr6nFo0HJE1CEc.pdf', 1, NULL, 'https://www.linkedin.com/in/fabian-balazs-krisztian', '', 0, 0, '2024-02-02 02:09:09', '2024-02-02 02:09:09'),
('9b3c78ab-8b9b-4350-8bdb-793f4ee6ab36', 18, 'Kazmi Syeda jaweria ', 'Jaweriakazmi04@gmail.com', 'University of Debrecen', 'photos/XKWVmXmG9AcPnNzsFNXG757koqmcjPs9FlMq5B3c.jpg', 'Bachelor in business administration and management ', 'Economics and Business', 'I have strong communication and problem solving skills along with leadership skills I also have strong knowledge in excel.\n', 'curriculums/USpJDrmRfGiZwoshuHB3FuxGpYBckfNMuWeOFlsi.pdf', 1, NULL, '', '', 0, 0, '2024-02-02 02:17:28', '2024-02-02 02:17:28'),
('9b3c7f15-c4c9-499c-bc42-2938f52cb2c3', 19, 'Dias MOLDAGALIYEV', 'diasmoldagaliyev@gmail.com', 'University of Debrecen', 'photos/blWJVFbcGjr0SVBFgY1jUKJnj7TRGtZxX04Ailie.jpg', 'Biochemical engineering ', 'Engineering', 'I am 20 years old. I have an american dream of working at a certain place from 9 to 5, and coming home to do my hobbies. \n', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-02 02:35:24', '2024-02-02 02:35:24'),
('9b3c8572-95a2-4b5d-9d83-19476b68b50f', 20, 'Israel Kumah', 'israelqwophi@gmail.com', 'University of Debrecen', 'photos/MFVEfmTkpUdeemAjWPiBAFX4E2M0LDfxpXexNVFg.jpg', 'Biochemical Engineering  BSc', 'Engineering', 'My name is Israel Kumah, a Ghanaian student at the university of Debrecen pursuing BSc. in Biochemical Engineering. I am dedicated and resourceful young professional, a quick learner with strong problem-solving abilities. I aspire to become a professional laboratory scientist. \n', 'default_value', 1, NULL, 'https://www.linkedin.com/in/israel-kumah-999563224/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app', '', 0, 0, '2024-02-02 02:53:12', '2024-02-02 02:53:12'),
('9b3c87f5-91cf-4c89-83c4-6a5a86b7d7a9', 21, 'Aymelek Yonat', 'melekyonat@gmail.com', 'University of Debrecen', 'photos/LYQk670lsWht5sIlXrAKTfnMuP8U3pjyDaMAZXOe.jpg', 'Biology BSc', 'Science and Technology', 'I am a biologist with 4 years experience in pharmaceutical industry.\nI am studying English Language Course at Debrecen University.\n', 'curriculums/BgH3qLsi7UaPT9fazHW6XQFcKbBho496RyHN1n0h.pdf', 1, NULL, '', '', 0, 0, '2024-02-02 03:00:13', '2024-02-02 03:00:13'),
('9b3c891a-4071-4b03-a7ab-c7b22c35bb17', 22, 'Abdelrahman Mansour', 'abdelrhmanwaled22190@gmail.com', 'University of Debrecen', 'photos/mnKrM9FsrUqAnxcFNOpSBA218OURagkAzquyNreV.jpg', 'bsc mechatornics engineering ', 'Engineering', 'Hi there! I\'m Abdelrahman Waled, a Mechatronics Engineering student from Egypt studying at the University of Debrecen in Hungary on a scholarship. I\'m passionate about the interdisciplinary nature of mechatronics and eager to gain practical experience through training and internships. I have strong problem-solving, technical, and communication skills and thrive in collaborative environments. If you have any opportunities or projects in the mechatronics field, let\'s connect and explore how I can contribute to your organization.\n', 'curriculums/sfspeHM8NpHx3kIVBx3LC2cp0JZOZ10mFo51mo7b.pdf', 1, NULL, 'https://www.linkedin.com/in/abdelrhman-waled-8352a41b3/', '', 0, 0, '2024-02-02 03:03:25', '2024-02-02 03:03:25'),
('9b3c8eb2-3bfd-439a-a041-ca8a08999a56', 23, 'SUMITKUMAR KANUBHAI', 'patanvadiya.sumit96@gmail.com', 'University of Debrecen', 'photos/fVieJ9Cq1l7aIYvuNRFOkJgDFTVtFdaTL1PX9CXB.jpg', 'Msc Engineering Management', 'Engineering', 'I aspire to leverage my MSc in Engineering Management with a specialization in Industrial Process Engineering to lead sustainable and innovative projects, optimizing industrial processes for efficiency and driving positive organizational impact.\n', 'default_value', 1, NULL, 'https://www.linkedin.com/in/sumitkumar-patanvadiya-041081144?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app', '', 0, 0, '2024-02-02 03:19:03', '2024-02-02 03:19:03'),
('9b3d9c23-3bc6-4a45-97cc-8c984bbf525c', 25, 'Eduardo Herculano ', 'Eduardo_amorim900@hotmail.com', 'University of Debrecen', 'photos/qfboTzyL9xhRK73VVzezyAQHWz5CFiAJEdGFR7Ll.jpg', 'Agriculture Engineering BSc', 'Engineering', 'My Goal is to get an opportunity in the market, aiming at professional advancement, diligently developing the activities assigned to me. Contribute to the faithful fulfilment of the mission of this company.\n', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-02 15:52:28', '2024-02-02 15:52:28'),
('9b3d9dc6-f3bc-431a-b5e8-453a19a0d702', 24, 'Muhammad Mana', 'muhammadmana321@gmail.com', 'University of Debrecen', 'photos/BtihjzYEwRBjYTEHmNakgipvm00gDaxlSu0eJ5Zo.jpg', 'Bachelor of Mechatronics Engineering ', 'Engineering', 'I am a quick learner who is always eager to overcome any obstacle in the process of learning. I plan to acquire an in-depth knowledge of mechatronics in order to apply it to the real world as the world itself is gravitating towards a technological innovation.\n', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-02 15:57:03', '2024-02-02 15:57:03'),
('9b3d9efb-f9a7-4157-b189-d8a0f3d4dce5', 26, 'Krisha Patel', 'krishapatel02112004@gmail.com', 'University of Debrecen', 'photos/H75yE1bkcHJXIA0uTGGk1vKIOLzn6KQDF5VX0PCi.jpg', 'Pharmacy  BSc', 'Health Sciences', 'I\'m a dedicated student at the University of Debrecen, currently pursuing a pharmacy foundation degree. Fueled by a passion for healthcare, I excel in communication, collaborating seamlessly with peers and envisioning future patient interactions. Rapid learning is my forte, enabling me to navigate the dynamic pharmaceutical landscape with ease.\n\nLooking ahead, I\'m open to opportunities in the job market, whether within the pharmaceutical industry or beyond. Eager to leverage my foundation degree, I aspire to contribute meaningfully to healthcare, whether through research, patient care, or innovation. Excited to carve my path and make a positive impact wherever my journey takes me!', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-02 16:00:26', '2024-02-02 16:00:26'),
('9b3da132-a2d2-4637-beaf-6c4d194d64ea', 27, 'Kocsis Lili', 'kocsislilike@gmail.com', 'University of Debrecen', 'photos/gAu7cUnCX7WQG4bodVAhrx85cfCVPjND75TkfRHZ.jpg', 'Kereskedelem és marketing ', 'Economics and Business', 'Debreceni Egyetem Gazdaságtudományi karán végeztem, kereskedelem és marketing szakon.\nEnergikus, nagy munkabírással rendelkező fiatal vagyok, aki az egyetemi évei alatt végig dolgozott vendéglátásban.\nRengeteg tapasztalatot gyűjtöttem az évek alatt, de ami a legfőbb, az a kommunikáció és értékesítés terén szerzett releváns tapasztalatom. \nÉletvidámságomat leginkább a többi emberből merítem, ugyanis feltölt ha emberek között lehetek, segíthetek nekik, esetleg bármely problémát együtt orvosolhatunk.', 'curriculums/n8UE7K7FJQnteaULDClwGpmimRqi063jASG46EmV.pdf', 1, NULL, '', '', 0, 0, '2024-02-02 16:06:37', '2024-02-02 16:06:37'),
('9b61502f-b903-41bd-ac8e-65ce59f26c7b', 54, 'Rowaida Eltaher Mahmoud ', 'Rowaidatbakry1@gmail.com', 'University of Debrecen ', 'photos/6bo7SfoEzJo6vE2ppR6JeEWMOWu06Iu7fRV0u0NR.jpg', 'Business Administration and management BSc', 'Economics and Business', 'I bring a versatile skill set to any job, valued by employers in different industries. With my strong communication, problem-solving, and teamwork skills, I thrive in dynamic environments. I\'m adaptable, show leadership potential, and pay close attention to detail, making me a valuable addition to any team. My customer-centric approach and commitment to excellence ensure I can excel in various roles.', 'curriculums/71TAI7G6TSrJlTxpDeDPHyDtCC4NFz3gpL5VXaY8.pdf', 1, NULL, '', '', 0, 0, '2024-02-20 09:49:54', '2024-02-20 09:49:54'),
('9b625ae3-ca08-4e6c-bee5-7eacfc1de2a1', 60, 'Mammadov Yusif', 'mammadovyusif36@gmail.com', 'University of Debrecen', 'photos/L4Nu6aBGCANIXiJuBwcJYgQbPZh9ma0BaFpcwdaS.jpg', 'Computer Science BSc', 'Informatics', 'Hello,i am a student in Debrecen University,i have coded in C,C++,Java and Html/CSS,now I study advanced Java(course name is Software Engineering) I had some projects in C++ and in Java,i am looking for internship,I won’t overrate my skills,i want to apply for beginner role,i am good with Logic,semantics,OOP,Data structures and many more. I offer 100% dedication,i am hard working and goal achiever at any cost (even if costs couple hours of sleep 😄). I am open to any computer related occupations', 'default_value', 1, NULL, 'https://www.linkedin.com/in/yusif-mammadov-a7a2152b6/', '', 0, 0, '2024-02-20 22:15:39', '2024-02-20 22:15:39'),
('9b634a86-6466-4ee5-b445-d39ba6ae9fca', 66, 'Savio Ariyan Gomes ', 'workwithsavio@gmail.com', 'University of Debrecen ', 'photos/l8Vhq2SzWbk8EEhMPAhu7r19zzNKUFSTqoUEv3Sk.jpg', 'Mechanical Engineering ', 'Engineering', 'I have worked with various organisations in my home country. Those include NGOS, Clubs and I also have expertise in building websites. I am a professional web developer.', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-21 09:25:43', '2024-02-21 09:25:43'),
('9b65521a-0b9d-4797-9680-5fd0422b2a05', 72, 'Asheer Adam', 'asheeradam2319@gmail.com', 'University of Debrecen', 'photos/aEBDynhKUGULXYoP866bpAivLd3lnVvcWMOqvnmE.jpg', 'MSc Engineering Management in Material Handling & Logistics', 'Engineering', 'Enthusiastic and dedicated Master of Science in Engineering Management candidate with a strong focus on Logistics, Material Handling, Supply Chain Management, Procurement & Warehouse operations. Aiming to leverage a blend of technical expertise and managerial acumen to drive efficiency and innovation in complex supply chain operations. With a solid foundation in engineering principles and a keen interest in optimizing processes, I am committed to contributing valuable insights to enhance the overall performance of organizations.', 'curriculums/5VuDe9pNiTxSL2U6RsKBXuz0pKb1W5L7fTkUWdNy.pdf', 1, NULL, 'https://www.linkedin.com/in/asheer-adam-9999551a1', '', 0, 0, '2024-02-22 09:38:34', '2024-02-22 09:38:34'),
('9b65d953-c512-41a3-b1cf-588d682a6de6', 5, 'Ragályi Petra', 'ragalyipetra@gmail.com', 'University of Debrecen ', 'photos/v25bBApGtdx0BRn3S9IzSIjR8VIBwSP0mqwfgs8A.jpg', 'Commerce and Marketing BSc', 'Economics and Business', 'I have different experiences from different fields. Such as working in HR, in Sales for Sagamore resort in the US. Also helped out in planning events, such as weddings, meetings for companies. ', 'curriculums/BFBUMGekLcwI7GMLtkDmmPvWY5Ptt10ATVnTLZBX.pdf', 1, NULL, '', '', 0, 0, '2024-02-22 15:56:41', '2024-02-22 15:56:41'),
('9b67f1ab-eff1-409e-b866-fe9a1450c436', 81, 'Martin Huszi', 'Lewartbob@gmail.com', 'University of Debrecen', 'photos/RV2M8qGaQtIHqu8hIC9roerhGBYL9ff51WnoLnqG.jpg', 'Business Administration ', 'Science and Technology', 'Im good at computers', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-23 16:56:25', '2024-02-23 16:56:25'),
('9b6a635f-b9cc-42b2-856c-f81889b2e2d6', 85, 'Zoljargal Ulziibadrakh', 'percussion_zoloo@yahoo.com', 'University of Debrecen', 'photos/SKp6HbEWwmWbHJFbm64N7HMcZTZWGmUfIsxHB7T1.jpg', 'Marketing and Music ', 'Economics and Business', 'I am a professional musician and marketer, currently conducting my PhD research in the field of arts marketing at the University of Debrecen.', 'curriculums/MdsAcunhj6XGyKcZdtb5em7ffXLjxADnjjPcnvVT.pdf', 1, NULL, '', '', 0, 0, '2024-02-24 22:06:00', '2024-02-24 22:08:03'),
('9b6a662b-3949-4c8b-9f12-9b776966b39a', 87, 'Youns Bashar Nayef', 'Younsbashar234@gmail.com', 'University of Debrecen ', 'photos/9TC68wfUng1Xwev8TuWXEBOV4QVhgaJDkkQVzmcD.jpg', 'General biology MSc', 'Science and Technology', 'I am a dedicated first-year biology student at the University of Debrecen with a passion for exploring the dynamic world of bio life and environment . My academic journey has equipped me with a solid foundation in biological concepts, and I am eager to apply my knowledge to real-world challenges and opportunities. I am a firm believer in the power of education to drive positive change and am actively seeking internships and projects that will allow me to gain practical experience while contributing to the success of organizations.', 'curriculums/eS5K2T9Sp2nWAnVZZEcv2WZH6LNk1yMojQ02O7d0.pdf', 1, NULL, 'https://www.linkedin.com/in/youns-nayef-80440a275?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app', '', 0, 0, '2024-02-24 22:13:49', '2024-02-24 22:13:49'),
('9b6a8ab3-dcf8-47ad-99c9-36b9cebd124e', 90, 'Abdelrahman Mansour', 'ak1500706@gmail.com', 'University of Debrecen', 'photos/u7RRVBOVZV7kD2bnQTd7HJKfc5XtYubg4w6kQN6a.jpg', 'Mechatronics Engineering Bsc', 'Engineering', 'Hello!\n\nThroughout the previous years, my experience as a Mechatronics student, airline\'s customer service agent and a head of the Presentation Committee at Enactus University Club, where I played a pivotal role in achieving significant success, has equipped me with unique skills that I believe align perfectly with the requirements needed in the job market.\n\nThank you for your time.', 'curriculums/Ukg2f30OFCIlMwClZKmDvadJsSeRYDGz4XRmJjxZ.pdf', 1, NULL, 'https://www.linkedin.com/in/abdelrahman-mansour-a5a831214/', '', 0, 0, '2024-02-24 23:55:58', '2024-02-24 23:55:58'),
('9b6aa765-792f-4882-92c5-6abdc53f6498', 92, 'Hossam Ehab Adel Massoud', 'hossam.hd2014@gmail.com', 'University of Debrecen', 'photos/zLe1PkvBOw5RGOWi0DRh7BB0P57KQHDvYjoquZLL.jpg', 'Computer Science Bsc', 'Informatics', 'Working in different industries made me eager to learn more from everything so whatever place i will be, i will give it 100% of my power to make everything as perfect as possible, learn more so i can make it more perfect. I worked with game development engine (unity) , front end, back end, web development, reinforcement learning, video editing, autoCAD. ', 'curriculums/PA8oigXWApLEesnLhZ8CiVdpEUtF29XVaYZZDcNx.pdf', 1, NULL, 'https://www.linkedin.com/in/hossam-massoud-6385b5241', '', 0, 0, '2024-02-25 01:16:12', '2024-02-25 01:16:12'),
('9b6b4893-76e3-426b-86ec-872a80ed8b32', 98, 'Tanisha mohanthy', 'tanishamohanthy@gmail.com', 'University of Developing ', 'photos/XwiceRWs636nG5jMGCfFLllSkVRswT0yb9AFMNCs.jpg', 'Medicine', 'Health Sciences', 'i am good with excel, word, powerpoint, numbers, supervision.', 'default_value', 1, NULL, 'https://www.linkedin.com/me?trk=p_mwlite_feed_updates-secondary_nav', 'https://www.linkedin.com/me?trk=p_mwlite_feed_updates-secondary_nav', 0, 0, '2024-02-25 08:46:54', '2024-02-25 08:46:54'),
('9b6b810a-7596-4de0-92af-cd3228aa609c', 104, 'Saltanat Beishenova ', 'saltanatb02@gmail.com', 'University of Debrecen ', 'photos/GM5M2AqHnT2rsvyiZ9gijPEDfSOpcVXWwjzVBMil.jpg', 'Computer Science Bsc', 'Informatics', 'I am a 2nd year Computer Science student with a float to get good in Data Science and backend development. ', 'curriculums/zKJH8sbzff8rg2MJdXclokjdHFqU7083NlznEyvy.pdf', 1, NULL, 'https://linkedin.com/in/substantivum', '', 0, 0, '2024-02-25 11:24:47', '2024-02-25 11:24:47'),
('9b6bc322-5bfb-413f-b26d-b750534d4d77', 106, 'Abid Muhammad Hamza ', 'abidhamza280@gmail.com', 'University of Debrecen ', 'photos/T6eb6MdbCs5vvIYzeCujAR3lKUWgOB9aZKE3hjFp.jpg', 'Biochemical Engineering ', 'Science and Technology', 'I am Biochemical Engineering student and will finish my degree this July. I am available for full time work as entry level as well as internee. ', 'curriculums/bLZWknYP7dI00Glwaw97JGfeFnu8FIhM8MZaH850.pdf', 1, NULL, '', '', 0, 0, '2024-02-25 14:29:36', '2024-02-25 14:29:36'),
('9b6bf14c-8583-4675-9ed2-805a6807f478', 109, 'Htin Htin Htet Aung ', 'htinhtinhtettaungh3a@gmail.com', 'University of Debrecen ', 'photos/vBsnIDJBz3f7ueSmgmKKheXSsuF6Y4jImdkwyR6f.jpg', 'Public Health ', 'Health Sciences', 'I am currently studying the bachelor of Public Health degree at the University and I’m very interested in Biostatistics and Environmental Health. I have 2 years experience in Customer Service, 2 years experience in Sales, 2 years experience in technical support and 1 year experience in Healthcare field. I’m a fast learner and please contact me anytime for part time jobs. Thank you.', 'curriculums/Xa4Ro4ougeIVlqZ6LJCCcgnowmGuYA7xgeiExUth.pdf', 1, NULL, 'http://linkedin.com/in/htin-htin-htet-aung-5a4753222', '', 0, 0, '2024-02-25 16:38:41', '2024-02-25 16:38:41'),
('9b6c12bc-ed78-44d6-ae55-e9cf0227e93a', 69, 'Alessandro Riano-Rencsár', 'alessandrorrxd@gmail.com', 'University of Debrecen ', 'photos/R8W7w3JUK5YLBg2SRkJBjgbFd7rIDtngH1N1bfym.jpg', 'Mechanical Engineering Bsc', 'Engineering', '-Actual mechanical engineering student \n-Experience with Interact (Rotary club) \n-Experience in varied Volunteer programs \n-Languages: Spanish/English/Medium Level of Hungarian \n-Looking for an Intership', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-25 18:12:11', '2024-02-25 18:14:19'),
('9b6c7e53-b934-4d73-931a-a198904f0dd6', 114, 'Spencer Ikuru', 'spencerikuruu@gmail.com', 'University of Debrecen', 'photos/joFqdZYeEh51VIT0ov9tpaXQjHinoqjaHLCIQhea.jpg', 'Computer Science BSc', 'Informatics', 'I have experience in customer service and microsoft office. I’m a student and a part-time DJ', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-25 23:13:01', '2024-02-25 23:13:01'),
('9b6d183f-e97d-49d2-8439-15d6df7da52e', 57, 'Láda Anita', 'ladaanita2004@gmail.con', 'Debreceni Egyetem', 'photos/qSgUr8MlOMDKlgDEsyXO4wRJsenK3KxkGXCqtVGT.png', 'Gazdálkodás és menedzsment ', 'Economics and Business', 'Elsősorban fejlődni szeretnék, illetve tapasztalatot szeretnék szerezni bármilyen munkakörben. Szívesen dolgozok együtt más emberekkel, de az egyedül végzendő monoton munka sem esik nehezemre.', 'default_value', 1, NULL, '', '', 0, 0, '2024-02-26 06:23:25', '2024-02-26 06:23:25'),
('9b6d7b5b-5e07-4749-9844-9f1a0bbc1b57', 116, 'Areej Alsobh ', 'areejalsobh@gmail.co', 'Hungarian university of Agriculture and life science ', 'photos/V3DrCBHIIXknnbVOwFlyHhutMgrS9zioZndaEOGI.jpg', 'Food science and I ', 'Agriculture, Food Sciences and Environmental Management', 'I have experience in chemical and food analyses, and a good knowledge in statistical analyses', 'curriculums/FGUUQ2asYAnY3QPP9BAovWdXWR9tTNASf2uMUtdL.pdf', 1, NULL, '', '', 0, 0, '2024-02-26 11:00:33', '2024-02-26 11:00:33'),
('9b6d93e4-535b-49e6-b200-2a43afa5efbd', 118, 'Malak Hiba ', 'malakhiba@mailbox.unideb.hu', 'University of Debrecen ', 'photos/31wtPxB723LQbAweTSvHy1bPA7TKcCo57tppZGDp.jpg', 'Mechatronics Engineering Bsc', 'Engineering', 'I am fluent in both English and Arabic as well as basics german. I can program/code using C, C++ and Python. I am able to use Autocad, multisim, symbols and lab view softwares. I can use Microsoft office (word, PowerPoint, excel). ', 'curriculums/W8v6k7bjpF4WRTdEjLWQarlm9THCXO0hgMCQWTUb.pdf', 1, NULL, 'https://www.linkedin.com/in/malak-hiba-816036266?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app', '', 0, 0, '2024-02-26 12:09:09', '2024-02-26 12:09:09'),
('9b7417eb-fdb9-4c19-beaa-224725e75f63', 126, 'Mohamed Awad', 'hamoodylilcarter@gmail.com', 'university of debrecen', 'photos/MH4Rrc1IBtmkSULjO2ZdOh1lNYEg1UAoGyMXGnxu.jpg', 'Business Administration and Management BSc', 'Economics and Business', 'Loyalty , self-discipline , performance , full responsibility.', 'curriculums/KCW5S4osoOPRZbeK8A4OtVaZaxAtqnToeaC5abdg.pdf', 1, NULL, 'https://www.linkedin.com/in/mohamed-awad-768161152/', '', 0, 0, '2024-02-29 17:53:18', '2024-02-29 17:53:18'),
('9b7a999d-79a2-47e5-abe4-dca390d47ca7', 129, 'Sakshi Kale ', 'kalesakshi48@gmail.com', 'University of Debrecen ', 'photos/TsN5osshdoF8OXC3T913gFgJR3KkmhuFe0U1zn13.jpg', 'Chemical engineering Msc', 'Science and Technology', 'I am a process design engineer with a passion for chemical engineering and renewable energy. I am currently pursuing my Master\'s degree in Advanced Chemical Engineering at University of Debrecen, Hungary, where I am learning to apply cutting-edge scientific and technological methods to solve complex challenges in the fields of pharmaceuticals, environmental sustainability, and energy production.\n\nMy most recent work experience was at Sam Enviro, a leading company in the design and implementation of renewable energy projects. As a proposal and process design engineer, I worked with a team of experts to develop and deliver innovative and cost-effective solutions for clients across various industries. I contributed to the design, optimization, and simulation of processes, equipment, and systems, using tools such as Aspen Plus, MATLAB, and AutoCAD. I also supported the preparation and presentation of technical proposals, reports, and documentation, ensuring high standards of quality and accuracy. Through this experience, I enhanced my skills in team management, product management, and food and beverage engineering.', 'curriculums/nNXzuCPcWEfWTX2ZLyWycSQ5FDTEyOeWZN7CBJGT.pdf', 1, NULL, 'https://www.linkedin.com/in/sakshi-kale-6109?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app', '', 0, 0, '2024-03-03 23:30:55', '2024-03-03 23:30:55'),
('9b7dd395-c870-4813-9983-23f96e0c3a59', 135, 'Desmond Owusu', 'Desmondowusu448@gmail.com', 'University of Debrecen ', 'photos/xGbjGUS1IpnN8NJQqD6PiVaSnkiOCHccv32tlQKc.jpg', 'MSc Animal Husbandry Engineering ', 'Agriculture, Food Sciences and Environmental Management', 'Motivated individual with strong ethic and working independently. Strong organizational and team collaboration skills. Willing to take on any task.', 'curriculums/tOy32CCddasUwRFdjDsOkMFQePPGZyX5vdWb0jyq.pdf', 1, NULL, '', '', 0, 0, '2024-03-05 14:00:30', '2024-03-05 14:00:30'),
('9b89cb65-2242-473f-a9df-221c0aac5785', 138, 'Aksh Hemantkumar Patel', 'akshgabs@gmail.com', 'University of Debrecen', 'photos/7PEnkgaeD5ahhTuMuvzO0nlyuiZvdBc01r0OpElk.jpg', 'Mechanical Engineering Bsc', 'Engineering', 'I\'m recent graduate from University of Debrecen in BSc Mechanical engineering and looking for work in which I can gain experience and learn more about the engineering industry, I am passionate about Research and Design and in the Aerospace and Automotive industry, and would love to work amongst experienced individuals in this field.', 'curriculums/Ffyo7AN38DBzoVeVEia4Ys11kSR3RnRNYbJ8uKxy.pdf', 1, NULL, 'https://www.linkedin.com/in/patelaksh', '', 0, 0, '2024-03-11 12:47:32', '2024-03-11 12:47:32'),
('9b8b9a9d-0a83-41a2-8c03-c276be7a2146', 143, 'Owanga winnie khamala', 'Khamalawinnie@gmail.com', 'University of debrecen', 'photos/93B8wvDmAWJ4UI2M06Sr8CcrWQokzojtFLqeX64z.jpg', 'Masters in environmental management engineering', 'Agriculture, Food Sciences and Environmental Management', 'I am hardworking ,self-disciplined  and quick learner and adapt easily to a new environment. ', 'curriculums/3LhszguE4cUfMo7R3odRr7vmIpuzt0JOs4L92MP8.pdf', 1, NULL, '', '', 0, 0, '2024-03-12 10:22:47', '2024-03-12 10:25:38'),
('9b8b9c6d-58b2-4e0d-a889-5d06e37925a5', 142, 'Ellewaththe Arachchillage Charuni Sewwandi Kumari', 'charunisewwandi10@gmail.com', 'University of Debrecen', 'photos/tA8cRb0gjshEElgyAbl1U65iixxmhMm92cdZdBIE.png', 'Agricultural Environmental Management Engineering MSc', 'Agriculture, Food Sciences and Environmental Management', 'I am Ellewaththe Arachchillage Charuni Sewwandi Kumari who is studying in Agricultural Environmental Management Engineering at University of Debrecen. \nI have BSc. Degree in Environmental Conservation and Management. I worked as Environmental Officer in foreign funded road construction projects. I have professional skills on Environmental Risk Assessment, Environmental Monitoring, informatics and Modeling, Toxicology, Environmental Chemistry. ', 'curriculums/6veFflUaUjC4PEgS50EN0jSAioSXCdjnUEOafsNQ.pdf', 1, NULL, '', '', 0, 0, '2024-03-12 10:27:51', '2024-03-12 10:27:51'),
('9b8fef76-a116-4a41-89c1-68c8d76aa16f', 55, 'Milena Egemberdieva', 'egemberdievaa12@gmail.com', 'University of Debrecen', 'photos/SXFnPNtMO83Kv71nhiJXXOZshvQKTduReBi45nei.jpg', 'Business Administration and Management ', 'Economics and Business', 'BA Student and Stipendium Hungaricum Scholarship Winner. ', 'default_value', 1, NULL, '', '', 0, 0, '2024-03-14 14:03:21', '2024-03-14 14:03:21'),
('9b915760-ea13-4605-95ee-33ed1ab2377b', 148, 'Daniela Alejandra Díaz Benavides', 'diazbdani20@gmail.com', 'University of Debrecen', 'photos/8koQkD7LligfGNAujPT6uyT5wPSuHWYZXyGVAhGY.jpg', 'MSc Public Health', 'Health Sciences', 'Dietitian nutritionist with interests oriented towards public nutrition, carrying out diagnostic functions of the food and nutritional sovereignty and security of the communities for the planning, implementation and evaluation of policies, plans, programmes and projects. With skills of proactivity, achievement orientation, assertive communication, planning, precision, negotiation, willingness to change, teamwork, empathy, and creativity.\n\nMember of the Student Committee of the Nutrition major.\nMember of the \"Nutrigenomics\" research group and the \"Food systems and human right to food\" research group\n\nThesis Proposal of the archer method value model for the creation of a nutritional evaluation and healthy gastronomy center at the Bogotá food bank (Internship).', 'default_value', 1, NULL, 'https://www.linkedin.com/in/daniela-d%C3%ADaz-benavides-253546229?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app', '', 0, 0, '2024-03-15 06:49:45', '2024-03-15 06:49:45'),
('9b92e8d5-ffcf-45a9-8dac-470af11877b6', 149, 'Nafis Daiyan Laskar', 'laskardaiyan@gmail.com', 'University of Debrecen', 'photos/Hj2jnvkfzseyQueBYDSJrFGlw0IJZriEiZv16s3v.jpg', 'Mechanical Engineering BSc', 'Engineering', 'A passionate and persevering student with active participation in extracurricular activities and proven leadership, management and problem-solving qualities. Various achievements in volunteering and club activities with a knack for learning new things.', 'curriculums/vuiIdwVk23908shUBfLyPuYCSqvH32lu1DbtbqGV.pdf', 1, NULL, '', '', 0, 0, '2024-03-16 01:32:18', '2024-03-16 01:32:18'),
('9b93e0ab-8eb3-4412-b9cb-98eef98469a9', 151, 'Tarcísio Henrique Menezes Sá', 'tarcisiomenezes2019@hotmail.com', 'Hungarian University of Agriculture and Life Sciences', 'photos/gHB7xCWJxH554V8PJQRVpMpLdlaybQCbPVdO08lq.png', 'Environmental engineering', 'Engineering', 'Frontend Developer and environmental engineering student.\n\nPlease feel free to check out my portfolio for all the detailed information you may have about me! There you will see contact, my social networks, github and my resume!', 'curriculums/y2FWSmrrSitu1XKPNCOtncZDdhZ7F0S41pcyUZPp.pdf', 1, 'JEy1K4DIxRL5LN6', 'https://www.linkedin.com/in/tarcísio-menezes-03b8a0233/', 'https://tarcisiohmenezes.com', 0, 0, '2024-03-16 13:05:18', '2024-03-22 12:01:03'),
('9b9478ee-e861-4a88-a416-d92ef79b522f', 157, 'Katharine Santos', 'katharinesantos@usp.br', 'USP', 'photos/fmi9vipZTdGTtIPwU1ePj1TC2uqdxyczhPPltaAS.jpg', 'Business', 'Economics and Business', 'Business', 'curriculums/zzkuSL3cpqiEqswGIuZ647uHb74HuRkXMfvjgy7m.pdf', 1, NULL, '', '', 0, 0, '2024-03-16 20:11:03', '2024-03-16 20:11:03'),
('9b94c216-6ef7-475d-ac02-a63e7eb2ff87', 160, 'Matheus Oliveira da Silva', 'matheus.mos@usp.br', 'University of Sao Paulo', 'photos/tS61dgo0DyKQ5lM7DNpxy5uujTgHDZNsMePjPMa6.png', 'Chemical Engineering', 'Engineering', 'Chemical Engineering student at University of Sao Paulo, Brazil, with international background in Economics and Business Management at BME, Hungary. As a repertoire, I worked in business development and I have knowledge in accounting, valuation and corporate finance.', 'curriculums/T93BikXTyC9OInXE5DrzsfVa7JTA8HaccjUd5xEk.pdf', 1, 'VXetSpECNusFP7G', 'https://www.linkedin.com/in/matheusoliveira-s/', '', 0, 0, '2024-03-16 23:35:37', '2024-03-16 23:35:37'),
('9b94c7ad-f770-4591-ba15-0fc0da4fdaaa', 161, 'Christian Fortunato Ribeiro', 'Christian720@hotmail.com', 'Pontificia Universidade Catolica', 'photos/Y2WJ86U6SfyupdUrYhA85VLGJQW9SDdO8HRAWdzE.jpg', 'Economy ', 'Economics and Business', 'I am looking for credit analyst opportunities ', 'default_value', 1, 'VXetSpECNusFP7G', '', '', 0, 0, '2024-03-16 23:51:15', '2024-03-16 23:51:15'),
('9b95caed-f1f3-4f2f-aecd-71f47c4935d4', 162, 'Bártfai Botond', 'botond.liko@gmail.com', 'Debreceni Egyetem', 'photos/ht1Cs7zXTaU7WD4eQvlVdEXoE2TggNNbDeE59OOn.png', 'Programtervező Informatikus Bsc', 'Informatics', 'Jelenleg dolgozom, de nem a szakmámban. Ezen szeretnék változtatni.\nPythont használok már 5 éve, és szeretek új programnyelvekbe belevágni.', 'default_value', 1, 'Nen', '', '', 0, 0, '2024-03-17 11:56:10', '2024-03-17 11:56:10'),
('9b966399-f9f4-4531-b641-c40628001a04', 163, 'Amanda da Silva Santos', 'amandassantoss2697@gmail.com', 'University of Debrecen', 'photos/lJDdXVXa8epWVVqQccj4C9Q1Q5PjZrKwQ5JQbv1s.jpg', 'Chemical Engineering', 'Science and Technology', '+5 years of experience with scientific research and development projects focusing on biotechnology, engineering, and control of industrial process variables. Experience in Design of Experiment (DOE) and statistical process control. I am passionate about science, technology and sustainable development and I love applying my skills in social causes.\n\n● Experience in problem analysis, solving and continius improvement tools (PDCA, root cause analysis, fishbone diagram, 5 Why’s and process mapping);\n● Great team worker with leadership experience;\n● Managment of key performance indicators (KPI’s);\n● Specialized Green Belt and Total Productive Maintenance; \n● Advanced skills in MS Office (Excel, PowerPoint and Word);\n● Self-motivated, strategic vision, strong organization and communication skills, proactive and hands on person;\n● Competence to work under pressure in a challenging and fast paced enviroment;\n● Flexibility to work in diferente teams and environments.', 'curriculums/j8aUUDKqvVjZGFIHdX4h1eyGWXOL581DOrt0aHec.pdf', 1, '0PGJ4xGT6aU7OEJ', 'https://www.linkedin.com/in/amandasantos26/', '', 0, 0, '2024-03-17 19:03:04', '2024-03-17 19:03:04'),
('9b98fc78-81ac-46a6-85ac-6a1cc4d62b3a', 171, 'Izabella Rocha', 'izarocha2016@gmail.com', 'Universidade de São Paulo', 'photos/0io3uvqS8vrTfkjnDAcKvsVqCjndxCJh8eRyAuLK.jpg', 'Business', 'Economics and Business', 'With four years of experience in Human Resources, I have cultivated expertise in international recruitment, particularly in high-complexity technology roles ranging from software developers to Chief Technology Officers (CTOs). My leadership role in a startup involved overseeing the entire people function, including recruitment, development, culture, performance evaluation, and compensation. This breadth of experience has equipped me with a comprehensive understanding of HR ecosystems and a proven track record of driving organizational success through strategic people management.', 'default_value', 1, 'VXetSpECNusFP7G', 'https://www.linkedin.com/in/izabella-rocha20/', '', 0, 0, '2024-03-19 02:02:10', '2024-03-19 02:02:10'),
('9b997073-56fb-41a7-a1e9-19506e449fbf', 172, 'Tóth Zsigmond', 'zsigmondtoth11@gmail.com', 'Debreceni egyetem', 'photos/BrbzRi2qoD6VyH7BzUZm0NK3u44HpWT0alJDJFNk.jpg', 'Osztatlan Agrármérnök MSC', 'Agriculture, Food Sciences and Environmental Management', 'Tóth Zsigmond vagyok.\nDebrecenben lakom, 21 éves vagyok.\nAgrármérnök másodéves hallgató.\nA debreceni Tóth Árpád gimnáziumban érettségiztem.\nRendelkezem Komplex angol B2 nyelvvizsgával, jogosítvánnyal illetve Ecdl modul vizsgáim is vannak.', 'default_value', 1, NULL, '', '', 0, 0, '2024-03-19 07:26:29', '2024-03-19 07:26:29'),
('9ba689ed-e303-4d08-a9d4-2c679d3fa7c6', 203, 'Peter Harry', 'osayemwenre17@gmail.com', 'university of debrecen', 'photos/anAN0My9W0apbASi4PZhhuURrbCquTkdit8C1jmL.jpg', 'Electrical Engineering BSc', 'Engineering', 'I aspire to be an Automobile engineer ', 'default_value', 1, '32u4MmezeLXH5Xf', '', '', 0, 0, '2024-03-25 19:43:29', '2024-03-25 19:43:29'),
('9ba68b39-5ba3-40be-8429-b23eb0a71e4c', 204, 'Jeremy Okolo', 'fwceejayy@gmail.com', 'University of Debrecen', 'photos/MnGqVhA2lLjBJWi22Fk4oni7JGJLqfW9qf1idWW2.jpg', 'Computer science Bsc', 'Informatics', 'I\'m studying computer science with hopes of bringing my software ideas to reality with the skills I learn.', 'default_value', 1, '32u4MmezeLXH5Xf', '', '', 0, 0, '2024-03-25 19:47:06', '2024-03-25 19:47:06'),
('9ba68beb-b2a2-41bf-999c-df2fa5a37d0e', 202, 'Marilyn Janta Chloe Bada', 'Chloejbada@gmail.com', 'University of Debrecen ', 'photos/fNa8YfISg4YNeqW5wY73erLLDjqfIXgCPFQ0hvMc.jpg', 'Business administration and Management ', 'Economics and Business', 'I am an ambitious and driven individual with a passion for making a positive impact on the world. My career goal is to become a CEO, where I can lead and inspire others to create meaningful change.  My skills in strategic thinking, communication, problem-solving, and team management, I am well-equipped to take on the challenges of a leadership role. ', 'curriculums/yDukIReKObDZjqx7xasYMX2dMdhXKFwJ0LHolF1A.pdf', 1, NULL, '', '', 0, 0, '2024-03-25 19:49:03', '2024-03-25 19:49:03'),
('9ba6929d-1c1e-4bdf-a3c0-8f24777990bb', 205, 'Joshua Bada', 'Joshuabada0@gmail.com', 'University of Debrecen ', 'photos/COUvihSrDUsHuPQa4G5vWxhladqegsV8itn8sq5N.jpg', 'Computer science ', 'Science and Technology', 'I am aspiring to be a computer scientist and posses some programming skills ', 'default_value', 1, '32u4MmezeLXH5Xf', '', '', 0, 0, '2024-03-25 20:07:46', '2024-03-25 20:07:46'),
('9ba9df03-f7d6-429b-91ad-63d6cb816e50', 208, 'Fekete Iván ', 'ivanfekete298@gmail.com', 'University of Debrecen ', 'photos/rkZwiTtfkbRcQsPWKXRuJqHRUWnN7CBRtD9HqHZu.jpg', 'Biochemical engineering BSc', 'Science and Technology', 'Fekete Iván vagyok, 21 éves és a Debreceni Egyetem elsôéves biomérnök hallgatója. Iskolás éveim alatt rengeteg diákmunkát váaltam ami fejlesztette a kapcsolati építés és probléma megoldó képességeim. Tanulmányi területemen keresek állást de bármilyen más irodai vagy könnyebb fizikai munkák is érdekelnek. C1-es angol nyelvvizsgávval rendelkezek.', 'default_value', 1, 'hN2Mq44YPL4bCaW', '', '', 0, 0, '2024-03-27 11:28:53', '2024-03-27 11:28:53'),
('9ba9fa28-4160-4b59-a52b-0f9912253bd8', 210, 'Balogh  Csaba', 'csa.balogh.0165@gmail.com', 'University of Debrecen', 'photos/x6xHUooTgleBA4n6o8dEBmJv0BWENMgf6sHx4rtd.jpg', 'General Medicine', 'Economics and Business', 'Ex computer engineering student and software engineer with some years of experience in devops, javascript, fullstack, etc.', 'curriculums/q1uLgpif3GMUkwk5UoAXSk1ezxlapnB4sugLgOsG.pdf', 1, 'FyoDlX4XMpD0yBh', 'https://www.linkedin.com/in/csaba-balogh-3a6451176?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app', '', 0, 0, '2024-03-27 12:44:47', '2024-03-27 12:44:47'),
('9baaa28c-fe21-454c-81cf-0fb39c1d9a95', 130, 'Ahmed Abualkheir', 'ahmed.abuelkhair2004@gmail.com', 'University of debrecen', 'photos/PQ3kVonTo8pEZCSL2WM3n3IGxEGFT7743wbi57Hz.jpg', 'Agricultural engineering BSc', 'Agriculture, Food Sciences and Environmental Management', 'Greetings! I\'m an enthusiastic agricultural engineering student, deeply fascinated by the intersection of technology and farming practices. My ultimate career aspiration is to become a proficient agricultural engineer, dedicated to developing innovative solutions for sustainable food production and resource management.', 'curriculums/19pf4HJ7OCMTTjGSqTsnKLgHyUwsdqaq2mncEFV1.pdf', 1, NULL, '', '', 0, 0, '2024-03-27 20:35:38', '2024-03-27 20:35:38'),
('9bad615a-b27b-4570-b95c-74373da0d8df', 215, 'David Ebem', 'davidec2100@gmail.com', 'University of Debrecen ', 'photos/hndRS94pZRjshjPn512xtjdr0WU2XfXo39432Mij.jpg', 'Pharmacy ', 'Economics and Business', 'I am a very skilled and hygienic individual, I speak excellent english and I have a very flexible schedule so I can work longer hours for you.', 'default_value', 1, NULL, '', '', 0, 0, '2024-03-29 05:20:49', '2024-03-29 05:20:49'),
('9bbc9196-c0d2-4b16-9263-3c59d2b19833', 222, 'Olta Rushiti', 'oltarushiti@gmail.com', 'University of Debrecen', 'photos/XmXLH3Up0MzEVoypvUTIoyny29DZB7l3vBOYwzd2.jpg', 'Biochemical Engineering Bsc', 'Science and Technology', 'Hello! I am Olta Rushiti and I come from Kosova. I am 19 years old, studying Biochemical Engineering at University of Debrecen. I loved science especially Chemistry since I was in primary school so it has been always my dream. I am looking forward to get my title as a Biochemical Engineer and specialize in Genetics related fields after. \nI have worked in one Italian restaurant in the city center of Debrecen and in a bakery so far. I have experience with Hungarian costumers and service. ', 'default_value', 1, 'I was given a QR code paper. ', 'http://linkedin.com/in/olta-rushiti-7bb6682b4', '', 0, 0, '2024-04-05 18:33:07', '2024-04-05 18:38:15'),
('9be6b5f3-0d78-4326-bf4a-3316a7b8d749', 224, 'Henrique Benitez Lopes', 'benitezlopes@gmail.com', 'Catholic University of São Paulo', 'photos/bZMwDo1dzz4qSh8DsrlBWUulYNNYwZrPX8vKienm.jpg', 'Social Sciences', 'Economics and Business', 'Graduated in Social Sciences and Economic Sciences with 10 years of experience in market research. I have analytical skills, understanding and interpreting quantitative and qualitative data, which allows me to analyze studies from various types of methods and economic sectors. I carried out studies in several areas, obtaining information and insights that allowed the launch of new consumer goods products, improvement of products and services that were already traditional in the market and cost reduction and increased productivity for companies. Additionally, I have extensive experience and knowledge about consumer behavior and market trends.', 'curriculums/OjIFBRi47Lgv7CHFD5HPMkjuxjZudWc21jDMIDyP.pdf', 1, 'tcEMbwWce9FvEm8', 'https://www.linkedin.com/in/benitez-lopes/', '', 0, 0, '2024-04-26 17:19:33', '2024-04-26 17:19:33');
INSERT INTO `notes` (`id`, `user_id`, `name`, `email`, `university`, `photo`, `degree`, `area`, `description`, `cv`, `accept`, `referral`, `linkedin`, `other_links`, `is_published`, `heart_count`, `created_at`, `updated_at`) VALUES
('9bf25bb3-9deb-4884-83e1-7a9ef87df77b', 225, 'Mena Golden ', 'menagolden15@gmail.com', 'University of Debrecen ', 'photos/bFaaI5eaJjROFZIFtFe8t3DNq4YVAO92yFdHJ0CK.jpg', 'Medicine ', 'Design', 'Skills, I love writing and sometimes sketching. I also love to help people in ways I can. I’d love to reach out to people through ways I can ', 'default_value', 1, NULL, '', '', 0, 0, '2024-05-02 12:17:08', '2024-05-02 12:21:32'),
('9bf25e95-c3fd-4444-8572-88a411d3c5c3', 226, 'Sarah  Evans Shem', 'sarahevanshemj@gmail.com', 'University of Debrecen ', 'photos/zEXIdYYTNvz2v1VkOuThZlHzVVYjmYTVEy2PkHYS.jpg', 'Basic medicine course', 'Economics and Business', 'I have dedication \nSkill( drawing, playing instruments)\nAnd I’ll say I’m pretty good with children ', 'default_value', 1, 'CWaireVDScfGZGM', '', '', 0, 0, '2024-05-02 12:25:12', '2024-05-02 12:25:12'),
('9c5985cf-812f-49c5-baf1-644f3c2ceaa9', 231, 'Serfőző Laura ', 'serfozolaura@gmail.com', 'University of Debrecen', 'photos/Zg2SiSfnDStUHygyYgIxWZkv7zqZ8htcQLCRM4ka.jpg', 'English', 'Humanities', 'My name is Laura, and I\'m looking for a flexible, yet creative job where I can use my best skills but also learn and polish new ones. ', 'curriculums/4UkhpDgxnMoAP6Wwluv0TH83qvPdww0EcMlrrJMw.pdf', 1, 'sp3EDjA9OgeTWfh', '', '', 0, 0, '2024-06-22 19:05:09', '2024-06-22 19:05:09'),
('9d14ccc3-e321-42f5-aa5e-1c0668790322', 238, 'Harmony Anesu Robson Bikoko', 'bikokoharmony1@gmail.com', 'University of Debrecen ', 'photos/cOb9vFkGOZzcoJIKtHvIoFK5JelQLiqQ9IjlvZZB.jpg', 'Mechatronics Engineering Bsc', 'Engineering', 'Motivated and enthusiastic student with a solid foundation in mechatronics engineering complemented by hands-on experience in a few projects and extracurricular activities . Skilled in a number of fields, I am eager to apply my knowledge and passion for mechatronics as an intern. Committed to continuous learning and contributing positively to any future projects I’m involved in.', 'default_value', 1, NULL, '', '', 0, 0, '2024-09-23 21:23:22', '2024-09-23 21:23:22');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
